-- Add new LeadStatus enum values (must be in a separate transaction from using them)
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'AFSPRAAK_INGEPLAND';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'INSTALLATIE_GEPLAND';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'BETALING_50';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'INSTALLATIE_GEDAAN';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'BETALING_100';
